spring:
  application:
    name: eureka-server
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8761

eureka:
  client:
    #these are false only for server config
    #for clients it will be true
    fetch-registry: false
    register-with-eureka: false
